FROM node:23-alpine AS development-dependencies-env
COPY . /app
WORKDIR /app
RUN npm ci

FROM node:23-alpine AS production-dependencies-env
COPY ./package.json package-lock.json /app/
WORKDIR /app
RUN npm ci --omit=dev

FROM node:23-alpine AS build-env
COPY . /app/
COPY --from=development-dependencies-env /app/node_modules /app/node_modules
WORKDIR /app
RUN npm run build

# Final stage for development
FROM node:23-alpine AS dev-env
COPY . /app/
COPY --from=development-dependencies-env /app/node_modules /app/node_modules
WORKDIR /app
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
