services:
  lifehub-backend:
    build:
      context: backend/
    container_name: lifehub-backend
    environment:
      - ENVIRONMENT=production
      - UVICORN_HOST=0.0.0.0
      - DB_HOST=host.docker.internal
      - DB_NAME=lifehub
      - FRONTEND_URL=http://lifehub-frontend
      - VAULT_ADDR=http://host.docker.internal:8200
      - VAULT_APPROLE_ROLE_ID=${VAULT_APPROLE_ROLE_ID}
      - VAULT_APPROLE_SECRET_ID=${VAULT_APPROLE_SECRET_ID}
    networks:
      - lifehub-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lifehub-frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: lifehub-frontend
    environment:
      - ENVIRONMENT=production
      - VITE_BACKEND_URL=http://lifehub-backend:8000
    ports:
      - "80:5173"
    depends_on:
      - lifehub-backend
    networks:
      - lifehub-net

networks:
  lifehub-net:
    driver: bridge
