services:
  lifehub-backend:
    build:
      context: backend/
    container_name: lifehub-backend
    environment:
      - ENVIRONMENT=production
      - UVICORN_HOST=0.0.0.0
      - DB_HOST=host.docker.internal
      - DB_NAME=lifehub
      - VAULT_ADDR=http://host.docker.internal:8200
      - VAULT_APPROLE_ROLE_ID=${VAULT_APPROLE_ROLE_ID}
      - VAULT_APPROLE_SECRET_ID=${VAULT_APPROLE_SECRET_ID}
      - REDIS_HOST=lifehub-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - lifehub-redis
    networks:
      - lifehub-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  lifehub-frontend:
    build:
      context: frontend/
    container_name: lifehub-frontend
    environment:
      - ENVIRONMENT=production
      - NODE_ENV=production
      - BACKEND_URL=http://lifehub-backend:8000
      - SESSION_SECRET=${SESSION_SECRET} # Not ideal to store as env, but for now it'll do
    ports:
      - "3000:3000"
    depends_on:
      - lifehub-backend
    networks:
      - lifehub-net

  lifehub-redis:
    image: redis:latest
    container_name: lifehub-redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    networks:
      - lifehub-net

networks:
  lifehub-net:
    driver: bridge
