services:
  lifehub-mariadb:
    image: mariadb:latest
    container_name: lifehub-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  lifehub-backend:
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    container_name: lifehub-backend
    environment:
      - DB_HOST=lifehub-mariadb
      - DB_USER=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - DB_NAME=${MARIADB_DATABASE}
      - FRONTEND_URL=http://localhost
    ports:
      - "8000:8000"
    depends_on:
      - lifehub-mariadb
    volumes:
      - ./backend:/app

  lifehub-frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    container_name: lifehub-frontend
    environment:
      - VITE_BACKEND_URL=http://lifehub-backend:8000
    ports:
      - "80:5173"
    depends_on:
      - lifehub-backend
    volumes:
      - ./frontend:/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
  dbdata:
    driver: local
