services:
  lifehub-mariadb:
    image: mariadb:latest
    container_name: lifehub-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      VAULT_DB_USER: ${VAULT_DB_USER}
      VAULT_DB_PASSWORD: ${VAULT_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init-scripts/mariadb:/docker-entrypoint-initdb.d

  lifehub-vault:
    image: hashicorp/vault:latest
    container_name: lifehub-vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-root-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    depends_on:
      - lifehub-mariadb
    volumes:
      - vault-data:/vault/data

  lifehub-backend:
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    container_name: lifehub-backend
    environment:
      - DB_HOST=lifehub-mariadb
      - DB_USER=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - DB_NAME=${MARIADB_DATABASE}
      - FRONTEND_URL=http://localhost
      - VAULT_ADDR=http://lifehub-vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_DB_USER=${VAULT_DB_USER}
      - VAULT_DB_PASSWORD=${VAULT_DB_PASSWORD}
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      - lifehub-mariadb
      - lifehub-vault
    volumes:
      - ./backend:/app

  lifehub-frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    container_name: lifehub-frontend
    environment:
      - VITE_BACKEND_URL=http://lifehub-backend:8000
      - VITE_SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "80:5173"
    depends_on:
      - lifehub-backend
    volumes:
      - ./frontend:/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
  dbdata:
    driver: local
  vault-data:
    driver: local
