/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard._index'
import { Route as DashboardFinanceImport } from './routes/dashboard.finance'
import { Route as DashboardFinanceCallbackImport } from './routes/dashboard.finance.callback'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/_index',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFinanceRoute = DashboardFinanceImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFinanceCallbackRoute = DashboardFinanceCallbackImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => DashboardFinanceRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_index': {
      id: '/dashboard/_index'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/finance/callback': {
      id: '/dashboard/finance/callback'
      path: '/callback'
      fullPath: '/dashboard/finance/callback'
      preLoaderRoute: typeof DashboardFinanceCallbackImport
      parentRoute: typeof DashboardFinanceImport
    }
  }
}

// Create and export the route tree

interface DashboardFinanceRouteChildren {
  DashboardFinanceCallbackRoute: typeof DashboardFinanceCallbackRoute
}

const DashboardFinanceRouteChildren: DashboardFinanceRouteChildren = {
  DashboardFinanceCallbackRoute: DashboardFinanceCallbackRoute,
}

const DashboardFinanceRouteWithChildren =
  DashboardFinanceRoute._addFileChildren(DashboardFinanceRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFinanceRoute: typeof DashboardFinanceRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFinanceRoute: DashboardFinanceRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/finance': typeof DashboardFinanceRouteWithChildren
  '/dashboard/finance/callback': typeof DashboardFinanceCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/finance': typeof DashboardFinanceRouteWithChildren
  '/dashboard/finance/callback': typeof DashboardFinanceCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/_index': typeof DashboardIndexRoute
  '/dashboard/finance': typeof DashboardFinanceRouteWithChildren
  '/dashboard/finance/callback': typeof DashboardFinanceCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/finance'
    | '/dashboard/finance/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/finance'
    | '/dashboard/finance/callback'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/_index'
    | '/dashboard/finance'
    | '/dashboard/finance/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/login",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/_index",
        "/dashboard/finance"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/dashboard/_index": {
      "filePath": "dashboard._index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/finance": {
      "filePath": "dashboard.finance.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/finance/callback"
      ]
    },
    "/dashboard/finance/callback": {
      "filePath": "dashboard.finance.callback.tsx",
      "parent": "/dashboard/finance"
    }
  }
}
ROUTE_MANIFEST_END */
